/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/cartonizzazioni": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crea Cartonizzazione */
        post: operations["crea_cartonizzazione_cartonizzazioni_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cartonizzazioni/etichette-colli": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Etichette Colli
         * @description Etichette per ogni collo interno (WP50/WP40), lotto/quantità —
         *     quella che conta ai fini di tracciabilità. Distinta dall'etichetta
         *     scatolone (riepilogo) e dall'etichetta ufficiale del corriere.
         */
        post: operations["etichette_colli_cartonizzazioni_etichette_colli_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cartonizzazioni/{order_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cartonizzazione Ordine Reale
         * @description Cartonizzazione di un ordine reale, letto da viscotta.orders/order_items.
         */
        get: operations["cartonizzazione_ordine_reale_cartonizzazioni__order_number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cartonizzazioni/{order_number}/etichette-colli": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Etichette Colli Ordine Reale
         * @description Etichette collo (WP50/WP40) per un ordine reale, letto dal DB.
         *     Lotto/scadenza reali da easyfatt.tmovmagazz (ultimo carico per SKU);
         *     se uno SKU non ha mai avuto un carico in EasyFatt resta il placeholder.
         *
         *     con_lotto=false: stampa in anticipo, quando solo alcuni SKU dell'ordine
         *     sono già stati prodotti (es. un ordine con più prodotti, di cui oggi è
         *     uscito dal laboratorio solo il primo) — lotto/scadenza verrebbero
         *     disallineati per il resto dell'ordine, quindi vengono omessi per tutta
         *     l'etichetta. Il barcode resta comunque (GTIN da solo, senza lotto):
         *     identifica il prodotto anche quando lotto/scadenza non sono ancora
         *     affidabili.
         */
        get: operations["etichette_colli_ordine_reale_cartonizzazioni__order_number__etichette_colli_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cartonizzazioni/{order_number}/etichette-scatolone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Etichette Scatolone Ordine Reale
         * @description Etichetta scatolone (una per collo di spedizione): riepilogo interno
         *     di cosa contiene, con dati reali dell'ordine (cliente, data consegna).
         *     Distinta dalle etichette collo WP50/WP40 e dall'etichetta ufficiale del
         *     corriere (DHL/BRT), che resta da applicare a parte alla conferma
         *     spedizione.
         */
        get: operations["etichette_scatolone_ordine_reale_cartonizzazioni__order_number__etichette_scatolone_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cartonizzazioni/colli/conferma": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Conferma Collo Scansionato
         * @description Conferma di fine linea: il reparto scansiona il barcode già stampato
         *     sull'etichetta scatolone (Code128 "<ordine>-NN") — nessuna digitazione
         *     manuale, nessun nuovo strumento in laboratorio. Idempotente: scansionare
         *     due volte lo stesso collo per errore non è un errore. 422 se l'indice
         *     non esiste nella cartonizzazione attuale dell'ordine (es. barcode di un
         *     ordine sbagliato, o cartonizzazione cambiata dopo la stampa).
         */
        post: operations["conferma_collo_scansionato_cartonizzazioni_colli_conferma_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cartonizzazioni/{order_number}/colli": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stato Colli Ordine
         * @description Stato delle conferme di fine linea per un ordine: quanti colli sono
         *     stati scansionati, quali mancano. Usare prima di confermare la
         *     spedizione (POST /spedizioni/{id}/conferma ha effetto reale).
         */
        get: operations["stato_colli_ordine_cartonizzazioni__order_number__colli_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cartonizzazioni/{order_number}/colli/{indice_collo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Annulla Conferma Collo
         * @description Annulla la conferma di un collo (errore di scansione).
         */
        delete: operations["annulla_conferma_collo_cartonizzazioni__order_number__colli__indice_collo__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cartonizzazioni/piano-giorno/{data_consegna}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Piano Giorno
         * @description Piano di cartonizzazione del giorno: un PDF A4, 4 ordini per pagina
         *     (2×2, linee di taglio), da stampare e allegare fisicamente a ogni ordine
         *     in laboratorio — documento ufficiale pre-produzione. Un ordine per
         *     ritaglio: le etichette collo WP50/WP40 (lotto/scadenza reali) arrivano
         *     dopo, a produzione fatta.
         */
        get: operations["piano_giorno_cartonizzazioni_piano_giorno__data_consegna__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spedizioni/valida/{order_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Valida Spedizione
         * @description Quota la spedizione di un ordine reale via MyDHL API (POST /rates) —
         *     nessuna spedizione viene creata, nessuna etichetta emessa: è la
         *     "bozza" emulata. Combina cartonizzazione (pesi scatoloni) e indirizzo
         *     cliente da DB.
         */
        post: operations["valida_spedizione_spedizioni_valida__order_number__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spedizioni": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crea Bozza Spedizione
         * @description Crea la bozza (stato 'bozza'): quota via /rates e salva su DB.
         *     Nessuna chiamata DHL con effetto reale — solo /rates, come /valida.
         */
        post: operations["crea_bozza_spedizione_spedizioni_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spedizioni/{spedizione_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dettaglio Spedizione */
        get: operations["dettaglio_spedizione_spedizioni__spedizione_id__get"];
        put?: never;
        post?: never;
        /**
         * Elimina Bozza Spedizione
         * @description Cancella SOLO se ancora in stato 'bozza' — nessuna chiamata DHL con
         *     effetto reale è mai avvenuta per una bozza, quindi non c'è nulla da
         *     annullare lato DHL.
         */
        delete: operations["elimina_bozza_spedizione_spedizioni__spedizione_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spedizioni/{spedizione_id}/conferma": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Conferma Spedizione
         * @description bozza -> confermata. QUESTA CHIAMATA HA EFFETTO REALE: crea la
         *     spedizione DHL vera con relativo costo (dhl.crea_spedizione). Va
         *     invocata solo dopo controllo umano della bozza (GET /spedizioni/{id}).
         *
         *     Gate: rifiuta (409) se il reparto non ha ancora scansionato tutti i
         *     colli dell'ordine (vedi POST /cartonizzazioni/colli/conferma) — senza
         *     questo controllo si potrebbe confermare (costo reale, ritiro reale)
         *     una spedizione con uno scatolone ancora aperto sul tavolo.
         */
        post: operations["conferma_spedizione_spedizioni__spedizione_id__conferma_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spedizioni/{spedizione_id}/etichetta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Etichetta Spedizione
         * @description PDF etichetta ufficiale DHL — solo per spedizioni 'confermata'/'ritirata'.
         */
        get: operations["etichetta_spedizione_spedizioni__spedizione_id__etichetta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spedizioni/{spedizione_id}/pickup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Richiedi Pickup Spedizione
         * @description confermata -> ritirata. QUESTA CHIAMATA HA EFFETTO REALE: prenota
         *     il ritiro DHL vero (dhl.richiedi_pickup). data_pickup di default
         *     domani (i ritiri lo stesso giorno spesso non sono più prenotabili
         *     dopo il cutoff — vedi pickupCapabilities in /rates).
         */
        post: operations["richiedi_pickup_spedizione_spedizioni__spedizione_id__pickup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RichiestaCartonizzazione */
        RichiestaCartonizzazione: {
            /** Order Number */
            order_number: string;
            /**
             * Cliente
             * @default
             */
            cliente: string;
            /** Righe */
            righe: components["schemas"]["RigaOrdine"][];
        };
        /** RigaOrdine */
        RigaOrdine: {
            /** Sku */
            sku: string;
            /** Qta */
            qta: number;
        };
        /** RisultatoCartonizzazione */
        RisultatoCartonizzazione: {
            /** Order Number */
            order_number: string;
            /** Scatoloni */
            scatoloni: components["schemas"]["Scatolone"][];
            /** N Scatoloni */
            n_scatoloni: number;
            /** Posti Liberi Ultimo */
            posti_liberi_ultimo: number;
            /** Peso Totale Kg */
            peso_totale_kg: number;
            /** Non Censiti */
            non_censiti: components["schemas"]["SkuNonCensito"][];
        };
        /** ScansioneCollo */
        ScansioneCollo: {
            /** Codice */
            codice: string;
        };
        /** ScatolaInterna */
        ScatolaInterna: {
            /** Formato */
            formato: string;
            /** Sku */
            sku: string;
            /** Pezzi */
            pezzi: number;
            /** Peso G */
            peso_g: number;
        };
        /** Scatolone */
        Scatolone: {
            /** Posti Usati */
            posti_usati: number;
            /** Contenuto */
            contenuto: components["schemas"]["ScatolaInterna"][];
            /** Peso G */
            peso_g: number;
        };
        /** SkuNonCensito */
        SkuNonCensito: {
            /** Sku */
            sku: string;
            /** Qta */
            qta: number;
        };
        /** SpedizioneResponse */
        SpedizioneResponse: {
            /** Id */
            id: string;
            /** Order Number */
            order_number: string;
            /** Corriere */
            corriere: string;
            /** Stato */
            stato: string;
            /** Product Code */
            product_code: string | null;
            /** Pesi Scatoloni Kg */
            pesi_scatoloni_kg: number[];
            /** Prezzo Stimato Eur */
            prezzo_stimato_eur: number | null;
            /** Shipment Tracking Number */
            shipment_tracking_number: string | null;
            /** Tracking Url */
            tracking_url: string | null;
            /** Dispatch Confirmation Number */
            dispatch_confirmation_number: string | null;
            /** Errore */
            errore: string | null;
            /** Creata At */
            creata_at: string;
            /** Confermata At */
            confermata_at: string | null;
            /** Ritirata At */
            ritirata_at: string | null;
        };
        /** StatoColli */
        StatoColli: {
            /** Order Number */
            order_number: string;
            /** N Totale */
            n_totale: number;
            /** Confermati */
            confermati: number[];
            /** Mancanti */
            mancanti: number[];
            /** Completo */
            completo: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    crea_cartonizzazione_cartonizzazioni_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RichiestaCartonizzazione"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RisultatoCartonizzazione"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    etichette_colli_cartonizzazioni_etichette_colli_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RichiestaCartonizzazione"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cartonizzazione_ordine_reale_cartonizzazioni__order_number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RisultatoCartonizzazione"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    etichette_colli_ordine_reale_cartonizzazioni__order_number__etichette_colli_get: {
        parameters: {
            query?: {
                con_lotto?: boolean;
            };
            header?: never;
            path: {
                order_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    etichette_scatolone_ordine_reale_cartonizzazioni__order_number__etichette_scatolone_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conferma_collo_scansionato_cartonizzazioni_colli_conferma_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScansioneCollo"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatoColli"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stato_colli_ordine_cartonizzazioni__order_number__colli_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatoColli"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    annulla_conferma_collo_cartonizzazioni__order_number__colli__indice_collo__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_number: string;
                indice_collo: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatoColli"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    piano_giorno_cartonizzazioni_piano_giorno__data_consegna__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                data_consegna: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    valida_spedizione_spedizioni_valida__order_number__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crea_bozza_spedizione_spedizioni_post: {
        parameters: {
            query: {
                order_number: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpedizioneResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dettaglio_spedizione_spedizioni__spedizione_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spedizione_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpedizioneResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    elimina_bozza_spedizione_spedizioni__spedizione_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spedizione_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conferma_spedizione_spedizioni__spedizione_id__conferma_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spedizione_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpedizioneResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    etichetta_spedizione_spedizioni__spedizione_id__etichetta_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spedizione_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    richiedi_pickup_spedizione_spedizioni__spedizione_id__pickup_post: {
        parameters: {
            query?: {
                data_pickup?: string | null;
            };
            header?: never;
            path: {
                spedizione_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpedizioneResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
